export const getMockInfrastructureData = (profile = 'pb', region = 'us-east-1') => {
  return {
    meta: {
      profile: profile || 'pb',
      region: region || 'us-east-1',
      lastUpdated: new Date().toISOString(),
      isMock: true,
      accountAlias: 'pricebook-production-aws',
      accountId: '710189071917'
    },
    summary: {
      totalClusters: 4,
      totalServices: 12,
      totalRunningTasks: 48,
      totalDesiredTasks: 48,
      totalContainerInstances: 10,
      totalStandaloneEc2: 5,
      totalEc2Instances: 15,
      totalAllocatedCpu: '28 vCPU',
      totalAllocatedMemory: '64.5 GB',
      totalS3Buckets: 18,
      totalS3StorageBytes: 387589000000, // ~387 GB
      totalS3ObjectCount: 2450800,
      totalRdsInstances: 4,
      totalRdsStorageGb: 1250,
    },
    ecs: {
      clusters: [
        {
          name: 'production',
          arn: 'arn:aws:ecs:us-east-1:710189071917:cluster/production',
          status: 'ACTIVE',
          runningTasksCount: 32,
          pendingTasksCount: 0,
          activeServicesCount: 6,
          registeredContainerInstancesCount: 6,
          capacityProviders: ['production-pricebook-admin', 'production-pricebook-distribuitor-new', 'production-pricebookplus'],
          services: [
            {
              name: 'pricebook-distribuitor',
              arn: 'arn:aws:ecs:us-east-1:710189071917:service/production/pricebook-distribuitor',
              status: 'ACTIVE',
              desiredCount: 6,
              runningCount: 6,
              pendingCount: 0,
              launchType: 'EC2',
              taskDefinition: 'pricebook-distribuitor:42',
              cpuPerTask: '1024 (1 vCPU)',
              memoryPerTask: '2048 MiB (2 GB)',
              totalCpu: '6 vCPU',
              totalMemory: '12 GB',
              instancesCount: 3,
              instances: ['i-0a8b9c1d2e3f4a101', 'i-0b9c0d1e2f3a4b102', 'i-0c0d1e2f3a4b5c103'],
              taskArns: [
                'arn:aws:ecs:us-east-1:710189071917:task/production/1a2b3c4d5e',
                'arn:aws:ecs:us-east-1:710189071917:task/production/2b3c4d5e6f',
                'arn:aws:ecs:us-east-1:710189071917:task/production/3c4d5e6f7a',
                'arn:aws:ecs:us-east-1:710189071917:task/production/4d5e6f7a8b',
                'arn:aws:ecs:us-east-1:710189071917:task/production/5e6f7a8b9c',
                'arn:aws:ecs:us-east-1:710189071917:task/production/6f7a8b9c0d'
              ]
            },
            {
              name: 'pricebookplus',
              arn: 'arn:aws:ecs:us-east-1:710189071917:service/production/pricebookplus',
              status: 'ACTIVE',
              desiredCount: 8,
              runningCount: 8,
              pendingCount: 0,
              launchType: 'EC2',
              taskDefinition: 'pricebookplus:38',
              cpuPerTask: '512 (0.5 vCPU)',
              memoryPerTask: '1024 MiB (1 GB)',
              totalCpu: '4 vCPU',
              totalMemory: '8 GB',
              instancesCount: 3,
              instances: ['i-0a8b9c1d2e3f4a101', 'i-0b9c0d1e2f3a4b102', 'i-0d1e2f3a4b5c6d104'],
              taskArns: [
                'arn:aws:ecs:us-east-1:710189071917:task/production/7a8b9c0d1e',
                'arn:aws:ecs:us-east-1:710189071917:task/production/8b9c0d1e2f'
              ]
            },
            {
              name: 'pricebook-admin',
              arn: 'arn:aws:ecs:us-east-1:710189071917:service/production/pricebook-admin',
              status: 'ACTIVE',
              desiredCount: 4,
              runningCount: 4,
              pendingCount: 0,
              launchType: 'EC2',
              taskDefinition: 'pricebook-admin:19',
              cpuPerTask: '1024 (1 vCPU)',
              memoryPerTask: '2048 MiB (2 GB)',
              totalCpu: '4 vCPU',
              totalMemory: '8 GB',
              instancesCount: 2,
              instances: ['i-0e2f3a4b5c6d7e105', 'i-0f3a4b5c6d7e8f106']
            },
            {
              name: 'pdf-generation-service',
              arn: 'arn:aws:ecs:us-east-1:710189071917:service/production/pdf-generation-service',
              status: 'ACTIVE',
              desiredCount: 6,
              runningCount: 6,
              pendingCount: 0,
              launchType: 'EC2',
              taskDefinition: 'pdf-gen:14',
              cpuPerTask: '1024 (1 vCPU)',
              memoryPerTask: '3072 MiB (3 GB)',
              totalCpu: '6 vCPU',
              totalMemory: '18 GB',
              instancesCount: 2,
              instances: ['i-0e2f3a4b5c6d7e105', 'i-0f3a4b5c6d7e8f106']
            },
            {
              name: 'notification-worker',
              arn: 'arn:aws:ecs:us-east-1:710189071917:service/production/notification-worker',
              status: 'ACTIVE',
              desiredCount: 4,
              runningCount: 4,
              pendingCount: 0,
              launchType: 'FARGATE',
              taskDefinition: 'notification-worker:8',
              cpuPerTask: '256 (0.25 vCPU)',
              memoryPerTask: '512 MiB (0.5 GB)',
              totalCpu: '1 vCPU',
              totalMemory: '2 GB',
              instancesCount: 0,
              instances: []
            },
            {
              name: 'auth-gateway',
              arn: 'arn:aws:ecs:us-east-1:710189071917:service/production/auth-gateway',
              status: 'ACTIVE',
              desiredCount: 4,
              runningCount: 4,
              pendingCount: 0,
              launchType: 'EC2',
              taskDefinition: 'auth-gateway:27',
              cpuPerTask: '512 (0.5 vCPU)',
              memoryPerTask: '1024 MiB (1 GB)',
              totalCpu: '2 vCPU',
              totalMemory: '4 GB',
              instancesCount: 2,
              instances: ['i-0a8b9c1d2e3f4a101', 'i-0b9c0d1e2f3a4b102']
            }
          ]
        },
        {
          name: 'staging',
          arn: 'arn:aws:ecs:us-east-1:710189071917:cluster/staging',
          status: 'ACTIVE',
          runningTasksCount: 10,
          pendingTasksCount: 0,
          activeServicesCount: 3,
          registeredContainerInstancesCount: 2,
          capacityProviders: ['staging-provider'],
          services: [
            {
              name: 'staging-pricebook-api',
              arn: 'arn:aws:ecs:us-east-1:710189071917:service/staging/staging-pricebook-api',
              status: 'ACTIVE',
              desiredCount: 4,
              runningCount: 4,
              pendingCount: 0,
              launchType: 'EC2',
              taskDefinition: 'staging-api:15',
              cpuPerTask: '512 (0.5 vCPU)',
              memoryPerTask: '1024 MiB (1 GB)',
              totalCpu: '2 vCPU',
              totalMemory: '4 GB',
              instancesCount: 2,
              instances: ['i-01122334455667788', 'i-09988776655443322']
            },
            {
              name: 'staging-pricebook-web',
              arn: 'arn:aws:ecs:us-east-1:710189071917:service/staging/staging-pricebook-web',
              status: 'ACTIVE',
              desiredCount: 4,
              runningCount: 4,
              pendingCount: 0,
              launchType: 'EC2',
              taskDefinition: 'staging-web:12',
              cpuPerTask: '512 (0.5 vCPU)',
              memoryPerTask: '1024 MiB (1 GB)',
              totalCpu: '2 vCPU',
              totalMemory: '4 GB',
              instancesCount: 2,
              instances: ['i-01122334455667788', 'i-09988776655443322']
            },
            {
              name: 'staging-bg-jobs',
              arn: 'arn:aws:ecs:us-east-1:710189071917:service/staging/staging-bg-jobs',
              status: 'ACTIVE',
              desiredCount: 2,
              runningCount: 2,
              pendingCount: 0,
              launchType: 'EC2',
              taskDefinition: 'staging-jobs:5',
              cpuPerTask: '256 (0.25 vCPU)',
              memoryPerTask: '512 MiB (0.5 GB)',
              totalCpu: '0.5 vCPU',
              totalMemory: '1 GB',
              instancesCount: 1,
              instances: ['i-01122334455667788']
            }
          ]
        },
        {
          name: 'uat',
          arn: 'arn:aws:ecs:us-east-1:710189071917:cluster/uat',
          status: 'ACTIVE',
          runningTasksCount: 4,
          pendingTasksCount: 0,
          activeServicesCount: 2,
          registeredContainerInstancesCount: 1,
          capacityProviders: ['uat-provider'],
          services: [
            {
              name: 'uat-app',
              arn: 'arn:aws:ecs:us-east-1:710189071917:service/uat/uat-app',
              status: 'ACTIVE',
              desiredCount: 2,
              runningCount: 2,
              pendingCount: 0,
              launchType: 'EC2',
              taskDefinition: 'uat-app:9',
              cpuPerTask: '512 (0.5 vCPU)',
              memoryPerTask: '1024 MiB (1 GB)',
              totalCpu: '1 vCPU',
              totalMemory: '2 GB',
              instancesCount: 1,
              instances: ['i-0aabbccddeeff0011']
            },
            {
              name: 'uat-worker',
              arn: 'arn:aws:ecs:us-east-1:710189071917:service/uat/uat-worker',
              status: 'ACTIVE',
              desiredCount: 2,
              runningCount: 2,
              pendingCount: 0,
              launchType: 'EC2',
              taskDefinition: 'uat-worker:4',
              cpuPerTask: '256 (0.25 vCPU)',
              memoryPerTask: '512 MiB (0.5 GB)',
              totalCpu: '0.5 vCPU',
              totalMemory: '1 GB',
              instancesCount: 1,
              instances: ['i-0aabbccddeeff0011']
            }
          ]
        },
        {
          name: 'preprod',
          arn: 'arn:aws:ecs:us-east-1:710189071917:cluster/preprod',
          status: 'ACTIVE',
          runningTasksCount: 2,
          pendingTasksCount: 0,
          activeServicesCount: 1,
          registeredContainerInstancesCount: 1,
          capacityProviders: ['preprod-provider'],
          services: [
            {
              name: 'preprod-pricebook-core',
              arn: 'arn:aws:ecs:us-east-1:710189071917:service/preprod/preprod-pricebook-core',
              status: 'ACTIVE',
              desiredCount: 2,
              runningCount: 2,
              pendingCount: 0,
              launchType: 'EC2',
              taskDefinition: 'preprod-core:3',
              cpuPerTask: '512 (0.5 vCPU)',
              memoryPerTask: '1024 MiB (1 GB)',
              totalCpu: '1 vCPU',
              totalMemory: '2 GB',
              instancesCount: 1,
              instances: ['i-01122334455667799']
            }
          ]
        }
      ]
    },
    ec2: {
      summary: {
        totalInstances: 15,
        ecsContainerInstancesCount: 10,
        standaloneInstancesCount: 5,
        runningCount: 14,
        stoppedCount: 1
      },
      instances: [
        // --- ECS Container Instances ---
        {
          instanceId: 'i-0a8b9c1d2e3f4a101',
          name: 'ECS Host - Prod Node 01',
          type: 't3.xlarge',
          category: 'ECS Container Instance',
          isEcsInstance: true,
          clusterName: 'production',
          state: 'running',
          publicIp: '54.210.45.12',
          privateIp: '10.0.1.45',
          az: 'us-east-1a',
          launchTime: '2026-06-15T08:30:00Z',
          vpcId: 'vpc-0a1b2c3d',
          platform: 'Amazon Linux 2 (ECS Optimized)'
        },
        {
          instanceId: 'i-0b9c0d1e2f3a4b102',
          name: 'ECS Host - Prod Node 02',
          type: 't3.xlarge',
          category: 'ECS Container Instance',
          isEcsInstance: true,
          clusterName: 'production',
          state: 'running',
          publicIp: '54.210.45.18',
          privateIp: '10.0.1.48',
          az: 'us-east-1b',
          launchTime: '2026-06-15T08:32:00Z',
          vpcId: 'vpc-0a1b2c3d',
          platform: 'Amazon Linux 2 (ECS Optimized)'
        },
        {
          instanceId: 'i-0c0d1e2f3a4b5c103',
          name: 'ECS Host - Prod Node 03',
          type: 't3.xlarge',
          category: 'ECS Container Instance',
          isEcsInstance: true,
          clusterName: 'production',
          state: 'running',
          publicIp: '54.210.45.24',
          privateIp: '10.0.1.52',
          az: 'us-east-1c',
          launchTime: '2026-06-15T08:35:00Z',
          vpcId: 'vpc-0a1b2c3d',
          platform: 'Amazon Linux 2 (ECS Optimized)'
        },
        {
          instanceId: 'i-0d1e2f3a4b5c6d104',
          name: 'ECS Host - Prod Node 04',
          type: 'c5.xlarge',
          category: 'ECS Container Instance',
          isEcsInstance: true,
          clusterName: 'production',
          state: 'running',
          publicIp: '54.210.46.10',
          privateIp: '10.0.2.14',
          az: 'us-east-1a',
          launchTime: '2026-07-01T10:15:00Z',
          vpcId: 'vpc-0a1b2c3d',
          platform: 'Amazon Linux 2 (ECS Optimized)'
        },
        {
          instanceId: 'i-0e2f3a4b5c6d7e105',
          name: 'ECS Host - Prod Node 05',
          type: 'c5.xlarge',
          category: 'ECS Container Instance',
          isEcsInstance: true,
          clusterName: 'production',
          state: 'running',
          publicIp: '54.210.46.19',
          privateIp: '10.0.2.22',
          az: 'us-east-1b',
          launchTime: '2026-07-01T10:20:00Z',
          vpcId: 'vpc-0a1b2c3d',
          platform: 'Amazon Linux 2 (ECS Optimized)'
        },
        {
          instanceId: 'i-0f3a4b5c6d7e8f106',
          name: 'ECS Host - Prod Node 06',
          type: 'c5.xlarge',
          category: 'ECS Container Instance',
          isEcsInstance: true,
          clusterName: 'production',
          state: 'running',
          publicIp: '54.210.46.33',
          privateIp: '10.0.2.35',
          az: 'us-east-1c',
          launchTime: '2026-07-01T10:25:00Z',
          vpcId: 'vpc-0a1b2c3d',
          platform: 'Amazon Linux 2 (ECS Optimized)'
        },
        {
          instanceId: 'i-01122334455667788',
          name: 'ECS Host - Staging Node 01',
          type: 't3.large',
          category: 'ECS Container Instance',
          isEcsInstance: true,
          clusterName: 'staging',
          state: 'running',
          publicIp: '34.200.12.80',
          privateIp: '10.0.10.15',
          az: 'us-east-1a',
          launchTime: '2026-05-10T14:00:00Z',
          vpcId: 'vpc-0a1b2c3d',
          platform: 'Amazon Linux 2 (ECS Optimized)'
        },
        {
          instanceId: 'i-09988776655443322',
          name: 'ECS Host - Staging Node 02',
          type: 't3.large',
          category: 'ECS Container Instance',
          isEcsInstance: true,
          clusterName: 'staging',
          state: 'running',
          publicIp: '34.200.12.92',
          privateIp: '10.0.10.28',
          az: 'us-east-1b',
          launchTime: '2026-05-10T14:05:00Z',
          vpcId: 'vpc-0a1b2c3d',
          platform: 'Amazon Linux 2 (ECS Optimized)'
        },
        {
          instanceId: 'i-0aabbccddeeff0011',
          name: 'ECS Host - UAT Node 01',
          type: 't3.medium',
          category: 'ECS Container Instance',
          isEcsInstance: true,
          clusterName: 'uat',
          state: 'running',
          publicIp: '52.90.111.44',
          privateIp: '10.0.20.09',
          az: 'us-east-1a',
          launchTime: '2026-04-02T11:20:00Z',
          vpcId: 'vpc-0a1b2c3d',
          platform: 'Amazon Linux 2 (ECS Optimized)'
        },
        {
          instanceId: 'i-01122334455667799',
          name: 'ECS Host - Preprod Node 01',
          type: 't3.medium',
          category: 'ECS Container Instance',
          isEcsInstance: true,
          clusterName: 'preprod',
          state: 'running',
          publicIp: '52.90.111.90',
          privateIp: '10.0.30.12',
          az: 'us-east-1b',
          launchTime: '2026-04-03T09:10:00Z',
          vpcId: 'vpc-0a1b2c3d',
          platform: 'Amazon Linux 2 (ECS Optimized)'
        },

        // --- Non-ECS Standalone EC2 Instances ---
        {
          instanceId: 'i-0ff00112233445566',
          name: 'DevOps Bastion / Jump Host',
          type: 't3.small',
          category: 'Standalone EC2 (Non-ECS)',
          isEcsInstance: false,
          clusterName: 'N/A',
          state: 'running',
          publicIp: '54.198.22.10',
          privateIp: '10.0.0.5',
          az: 'us-east-1a',
          launchTime: '2026-01-10T00:00:00Z',
          vpcId: 'vpc-0a1b2c3d',
          platform: 'Ubuntu 22.04 LTS'
        },
        {
          instanceId: 'i-0ee11223344556677',
          name: 'Jenkins CI/CD Worker',
          type: 'c5.2xlarge',
          category: 'Standalone EC2 (Non-ECS)',
          isEcsInstance: false,
          clusterName: 'N/A',
          state: 'running',
          publicIp: '54.198.22.45',
          privateIp: '10.0.0.88',
          az: 'us-east-1b',
          launchTime: '2026-02-18T16:00:00Z',
          vpcId: 'vpc-0a1b2c3d',
          platform: 'Ubuntu 22.04 LTS'
        },
        {
          instanceId: 'i-0dd22334455667788',
          name: 'Redis Cache Standalone',
          type: 'r5.large',
          category: 'Standalone EC2 (Non-ECS)',
          isEcsInstance: false,
          clusterName: 'N/A',
          state: 'running',
          publicIp: 'N/A (Private Only)',
          privateIp: '10.0.3.110',
          az: 'us-east-1a',
          launchTime: '2026-03-01T07:45:00Z',
          vpcId: 'vpc-0a1b2c3d',
          platform: 'Amazon Linux 2'
        },
        {
          instanceId: 'i-0cc33445566778899',
          name: 'OpenVPN Access Server',
          type: 't3.medium',
          category: 'Standalone EC2 (Non-ECS)',
          isEcsInstance: false,
          clusterName: 'N/A',
          state: 'running',
          publicIp: '54.221.88.99',
          privateIp: '10.0.0.250',
          az: 'us-east-1a',
          launchTime: '2026-01-05T12:00:00Z',
          vpcId: 'vpc-0a1b2c3d',
          platform: 'Ubuntu 22.04 LTS'
        },
        {
          instanceId: 'i-0bb44556677889900',
          name: 'Legacy Microservice Backup',
          type: 't2.micro',
          category: 'Standalone EC2 (Non-ECS)',
          isEcsInstance: false,
          clusterName: 'N/A',
          state: 'stopped',
          publicIp: 'N/A',
          privateIp: '10.0.4.77',
          az: 'us-east-1c',
          launchTime: '2025-11-20T10:00:00Z',
          vpcId: 'vpc-0a1b2c3d',
          platform: 'Amazon Linux 2'
        }
      ]
    },
    rds: {
      summary: {
        totalDatabases: 4,
        totalStorageGb: 1250,
        multiAzCount: 3,
        primaryEngine: 'PostgreSQL 15.4'
      },
      instances: [
        {
          dbIdentifier: 'pricebook-prod-postgres',
          engine: 'postgres',
          engineVersion: '15.4',
          instanceClass: 'db.r6g.xlarge',
          allocatedStorageGb: 500,
          maxAllocatedStorageGb: 2000,
          storageType: 'gp3',
          iops: 3000,
          multiAz: true,
          status: 'available',
          endpoint: 'pricebook-prod-postgres.c1a2b3c4d5e6.us-east-1.rds.amazonaws.com',
          port: 5432,
          createdTime: '2025-08-12T06:00:00Z'
        },
        {
          dbIdentifier: 'pricebook-analytics-db',
          engine: 'postgres',
          engineVersion: '15.4',
          instanceClass: 'db.m6g.xlarge',
          allocatedStorageGb: 400,
          maxAllocatedStorageGb: 1000,
          storageType: 'gp3',
          iops: 3000,
          multiAz: true,
          status: 'available',
          endpoint: 'pricebook-analytics-db.c1a2b3c4d5e6.us-east-1.rds.amazonaws.com',
          port: 5432,
          createdTime: '2025-10-01T09:30:00Z'
        },
        {
          dbIdentifier: 'pricebook-staging-db',
          engine: 'postgres',
          engineVersion: '15.4',
          instanceClass: 'db.t4g.large',
          allocatedStorageGb: 200,
          maxAllocatedStorageGb: 500,
          storageType: 'gp2',
          iops: null,
          multiAz: true,
          status: 'available',
          endpoint: 'pricebook-staging-db.c1a2b3c4d5e6.us-east-1.rds.amazonaws.com',
          port: 5432,
          createdTime: '2026-01-15T14:20:00Z'
        },
        {
          dbIdentifier: 'pricebook-uat-mysql',
          engine: 'mysql',
          engineVersion: '8.0.35',
          instanceClass: 'db.t3.medium',
          allocatedStorageGb: 150,
          maxAllocatedStorageGb: 300,
          storageType: 'gp2',
          iops: null,
          multiAz: false,
          status: 'available',
          endpoint: 'pricebook-uat-mysql.c1a2b3c4d5e6.us-east-1.rds.amazonaws.com',
          port: 3306,
          createdTime: '2026-03-10T11:00:00Z'
        }
      ]
    },
    s3: {
      summary: {
        totalBuckets: 18,
        totalSizeBytes: 387589000000,
        totalSizeFormatted: '387.58 GB',
        totalObjectCount: 2450800,
        storageLensEnabled: true,
        storageLensConfigId: 'default-account-lens'
      },
      buckets: [
        { name: 'pricebook-distributor-assets-prod', creationDate: '2025-05-10T08:00:00Z', region: 'us-east-1', estimatedSizeFormatted: '142.5 GB', estimatedObjects: 980500 },
        { name: 'pricebook-client-pdf-reports', creationDate: '2025-06-12T10:15:00Z', region: 'us-east-1', estimatedSizeFormatted: '88.2 GB', estimatedObjects: 450200 },
        { name: 'pricebook-db-backups-daily', creationDate: '2025-04-01T12:00:00Z', region: 'us-east-1', estimatedSizeFormatted: '95.0 GB', estimatedObjects: 1240 },
        { name: 'pricebook-application-logs-archive', creationDate: '2025-04-01T12:30:00Z', region: 'us-east-1', estimatedSizeFormatted: '34.8 GB', estimatedObjects: 890000 },
        { name: 'pricebook-staging-uploads', creationDate: '2025-07-20T14:45:00Z', region: 'us-east-1', estimatedSizeFormatted: '12.4 GB', estimatedObjects: 85000 },
        { name: 'pricebook-uat-temp-files', creationDate: '2025-09-10T09:00:00Z', region: 'us-east-1', estimatedSizeFormatted: '4.2 GB', estimatedObjects: 21000 },
        { name: 'pricebook-frontend-static-builds', creationDate: '2025-05-15T11:20:00Z', region: 'us-east-1', estimatedSizeFormatted: '1.8 GB', estimatedObjects: 14500 },
        { name: 'pricebook-cloudtrail-audit-logs', creationDate: '2025-04-01T00:00:00Z', region: 'us-east-1', estimatedSizeFormatted: '8.6 GB', estimatedObjects: 125000 },
        { name: 'pricebook-storage-lens-reports-710189071917', creationDate: '2025-11-01T10:00:00Z', region: 'us-east-1', estimatedSizeFormatted: '0.1 GB', estimatedObjects: 360 }
      ],
      storageLens: [
        {
          configId: 'default-account-lens',
          awsAccountId: '710189071917',
          status: 'ENABLED',
          exportFormat: 'Parquet / CSV',
          lastUpdated: '2026-08-17T23:59:59Z',
          metrics: {
            totalStorageBytes: '387.58 GB',
            objectCount: '2.45 Million',
            standardStorageGb: '290.4 GB',
            infrequentAccessGb: '75.2 GB',
            glacierStorageGb: '21.98 GB',
            uncategorizedBuckets: 0
          }
        }
      ]
    }
  };
};
